// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohrnyumykumqowqalfmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ocm55dW15a3VtcW93cWFsZm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4NjM0NDcsImV4cCI6MjA5ODQzOTQ0N30.hFiwP0pcprccWobYvPnwVnwGwzwhGs7PdrpUz_UA2WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});